// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Game
{
    public int GameId { get; set; }

    public string Title { get; set; }

    public decimal Price { get; set; }

    public DateOnly? ReleaseDate { get; set; }

    public int? DeveloperId { get; set; }

    public int? CategoryId { get; set; }

    public string ImageUrl { get; set; }

    public virtual GameCategory Category { get; set; }

    public virtual Developer Developer { get; set; }

    public virtual ICollection<Registration> Registrations { get; set; } = new List<Registration>();
}