// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Registration
{
    public int RegistrationId { get; set; }

    public int PlayerId { get; set; }

    public int GameId { get; set; }

    public DateTime RegistrationDate { get; set; }

    public virtual Game Game { get; set; }

    public virtual Player Player { get; set; }
}