// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class User
{
    public int UserId { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public DateTime JoinDate { get; set; }

    public int RoleId { get; set; }

    public virtual Player Player { get; set; }

    public virtual Role Role { get; set; }
}